### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by irishstu** [HubSpot/jquery-zoomer#2]
Is there a way to enable scrolling?

**Comment by adamschwartz** [comment]
This is not a supported feature of Zoomer due to the instability of CSS-scaled iFrames. In our tests, scrolling a zoomed iFrame caused rendering bugs in several browsers (at the time of this writing).

However, there are several workarounds you can try which may work fine for your particular use-case.

---

**Option 1**

Hide the `.zoomer-cover` to allow mouse events to enter the `iFrame`.

```
.zoomer-cover {
    display: none !important;
}
```

As Zoomer sets `overflow` to `hidden` on the `iFrame`, for Firefox support, you will also need to apply the following CSS:

```
iframe.to-be-zoomed {
    overflow: auto !important;
}
```

---

**Option 2**

Another option is to make the iFrame the height of its contents, making scrolling unnecessary.

Obtain the document height of the `iFrame` contents (after they've loaded), multiply this value by your `zoom` setting, and use javascript to apply this new height to a number of elements. With jQuery, this could look like the following:

```
var zoom = 0.5,
    $iframe = $('iframe'),
    src = 'http://example.com'
;

$iframe
    .load(function(){
        var newHeight = zoom * $(this.contentDocument).height();

        // setTimeout to ensure height set after Zoomer does its magic
        setTimeout(function(){
            $iframe.css('height', newHeight);
            $('.zoomer-cover, .zoomer-wrapper, .zoomer-small, .zoomer-loader').css('height', newHeight);
        }, 100);
    })
    .zoomer({
        zoom: zoom,
        width: 400
    })
    .zoomer('src', src) // Refresh the iFrame to trigger the load event
;
```

With this version, the zoomed `iFrame` will appear as tall as its contents necessitate.

---

**Option 3**

A final option is to do the same thing as **Option 2** (above), but remove `.zoomer-wrapper` from the set of elements to apply `newHeight` to and instead add the following CSS:

```
.zoomer-wrapper {
    overflow: auto !important;
    height: 300px /* desired height of scrollable area */ !important;
    width: 400px /* desired width of scrollable area */ !important;
}
```

With this method, the `iFrame` itself will still be the height of its contents, but only a 300px-by-400px area will be visible at a given time, and scrolling will be done via the wrapper element instead.

---

Hope this helps!

**Comment by irishstu** [comment]
Thanks Adam, appreciate the detailed reply. One solution I found was to shrink the contents of the iframe within the page that's being loaded by wrapping it in a div, but I haven't fully tested it.
